### ISSUE TITLE
Installation of Eigen

### ISSUE THREAD

**Issue by Mi-chael** [molspintron/HYDRA#3]
Apparently, Eigen can also be installed (partially?) on ubuntu using`apt install libeigen3-dev`. Is that maybe sufficient and an easier way to install it?

**Comment by SchneeziMichi** [comment]
Yes, this is also a possibility and probably more convenient if you are able to use it. But being able to just download and save the headers was one of the reasons we choose Eigen. We mention it because this way HYDRA can be used on systems that prohibit users from installing software, e.g. on a third party hpc cluster, without having to ask for Eigen to be installed.

**Comment by Mi-chael** [comment]
Alright. So I guess this can be closed, and maybe one points to that possibility in the readme(?)
